server:
  port: 8089
  error:
    whitelabel:
      enabled: false

spring:
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    root: info

info:
  name: ${project.name}
  description: ${project.description}
  version: ${project.version}

req-qa:
  version: @project.version@
  name: req-qa

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, shutdown
      cors:
        allowed-origins: "*"
        allowed-methods: OPTIONS, GET, POST
        allowed-headers: "*"
  endpoint:
    shutdown:
      enabled: false

taiga:
  baseUrl: "http://localhost:9000"
  secret: "TO_BE_DEFINED"
  customFieldName: "quality"
  username: "TO_BE_DEFINED"
  password: "TO_BE_DEFINED"
  granType: "password"

openreq:
  baseUrl: "http://localhost:9799"
  checkQuality: "/check-quality"
