server:
  port: 8089
  error:
    whitelabel:
      enabled: false

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    root: info

info:
  name: ${project.name}
  description: ${project.description}
  version: ${project.version}

req-qa:
  version: @project.version@
  name: req-qa

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, shutdown
      cors:
        allowed-origins: "*"
        allowed-methods: OPTIONS, GET, POST
        allowed-headers: "*"
  endpoint:
    shutdown:
      enabled: false

taiga:
  baseUrl: "http://localhost:8081"
  secret: "4002357aa9e2d26e83228b09cd050af84787e5e7"

open-req:
  baseUrl: "http://localhost:9799"
  checkQuality: "/check-quality"
